### ISSUE TITLE
Incorrect capitalization of folder name

### ISSUE THREAD

**Issue by Odyseus** [TedStumpf/RandomsGeneAssistant#1]
Hello, @TedStumpf.

When I initially installed your mod it didn't work at all. After trying several things I saw that one of your mod's folders was called **assemblies** instead of **Assemblies** (note the capitalization). I renamed the folder and the mod works as intended.

I should mention that I use Linux, not Windows. In Linux, most commonly used file systems are case-sensitive.

The following message from a Steam user reporting an issue might be related:

```
From: nm0i

Having "Mod Random's Gene Assistant did not load any content." error, pastebin: https://me0w.net/p/7b66ac560348.txt
Any thoughts?
```

And another one:

```
From:  jvzr

Once, I had the same error as @nm0i but only once. Is there a way I can help you debug this, Random? 
```

***

I'm writing this issue because as a basic Steam user I can't post messages anywhere on Steam.

**Comment by TedStumpf** [comment]
Thank you so much for telling me about this. As a windows user it would have taken me far to long to find a fix. I've updated the mod both here and on steam.

**Comment by Odyseus** [comment]
I'm glad that I could be of help. Keep up the good work. :+1:
